---
openapi: 3.0.1
info:
  title: mydatamood-survey
  version: v1
paths:
  "/categories":
    get:
      summary: query category data
      tags:
      - category
      parameters:
      - name: q
        in: query
        description: type of query to be run
        schema:
          type: string
      - name: limit
        in: query
        description: limit in the number of results returned
        schema:
          type: integer
      - name: reverse
        in: query
        description: flag to indicate the result ordering
        schema:
          type: boolean
      responses:
        '200':
          description: list of categories
          content:
            application/json:
              example:
              - category: landline_internet
                score: 8
              - category: race_cars
                score: 7
              - category: stock_investment
                score: 6.5
              schema:
                type: array
                name: categories
                items:
                  properties:
                    "$ref": "#/definitions/category"
        '422':
          description: unknown query type unprocessable entity
  "/interests":
    post:
      summary: load interest show by a user into a particular product
      tags:
      - interest
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/definitions/interest"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/definitions/interest"
  "/products":
    put:
      summary: load list of available products into the system
      tags:
      - product
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                type: array
                name: products
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      default: 1234abcd
                    name:
                      type: string
                      default: Car Insurance for any damage
                    category:
                      type: string
                      default: car_insurances
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    default: 1234abcd
                  name:
                    type: string
                    default: Car Insurance for any damage
                  category:
                    type: string
                    default: car_insurances
                required:
                - name
                - category
    get:
      summary: query product data
      tags:
      - product
      parameters:
      - name: q
        in: query
        description: type of query to be run
        schema:
          type: string
      - name: limit
        in: query
        description: limit in the number of results returned
        schema:
          type: integer
      - name: reverse
        in: query
        description: flag to indicate the result ordering
        schema:
          type: boolean
      responses:
        '200':
          description: list of products
servers:
- url: http://localhost:3000
  description: test server
- url: heroku
  description: production server
definitions:
  category:
    type: object
    properties:
      category:
        type: string
      score:
        type: number
    required:
    - category
  product:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      category_id:
        "$ref": "#/definitions/category"
      score:
        type: number
    required:
    - name
    - category
  user:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
    required:
    - id
  interest:
    type: object
    properties:
      user_id:
        type: integer
        example: asdfasdf123
      product_id:
        type: integer
        example: 1234abcd
      score:
        type: number
        example: 7
    required:
    - user_id
    - product_id
    - socre
