default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mydatamood-survey_development

test:
  <<: *default
  database: mydatamood-survey_test

production:
  <<: *default
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>